### ISSUE TITLE
解析少部分浮点数字符串有精度问题(版本:0.0.19)

### ISSUE THREAD

**Issue by dwing4g** [wycst/wast#2]
解析少部分浮点数字符串有精度问题, 跟JDK自带的解析不一致:
```
    public static void main(String[] args) {
        double d = 9.49113649602955E-309;
        String s = Double.toString(d);
        System.out.println(s); // 输出: 9.49113649602955E-309
        double d1 = ((List<Double>)io.github.wycst.wast.json.JSON.parse("[" + s + "]")).get(0);
        System.out.println(d1); // 输出: 9.491136496029548E-309
        double d2 = Double.parseDouble(s);
        System.out.println(d2); // 输出: 9.49113649602955E-309
        System.out.println(d1 == d2); // 输出: false
    }
```

另外, JSON.parse最好可以解析number,boolean字符串, 返回Number,Boolean类型.

**Comment by wycst** [comment]
> 解析少部分浮点数字符串有精度问题, 跟JDK自带的解析不一致:
> 
> ```
>     public static void main(String[] args) {
>         double d = 9.49113649602955E-309;
>         String s = Double.toString(d);
>         System.out.println(s); // 输出: 9.49113649602955E-309
>         double d1 = ((List<Double>)io.github.wycst.wast.json.JSON.parse("[" + s + "]")).get(0);
>         System.out.println(d1); // 输出: 9.491136496029548E-309
>         double d2 = Double.parseDouble(s);
>         System.out.println(d2); // 输出: 9.49113649602955E-309
>         System.out.println(d1 == d2); // 输出: false
>     }
> ```
> 
> 另外, JSON.parse最好可以解析number,boolean字符串, 返回Number,Boolean类型.

感谢反馈，会尽快修复

**Comment by wycst** [comment]
> 解析少部分浮点数字符串有精度问题, 跟JDK自带的解析不一致:
> 
> ```
>     public static void main(String[] args) {
>         double d = 9.49113649602955E-309;
>         String s = Double.toString(d);
>         System.out.println(s); // 输出: 9.49113649602955E-309
>         double d1 = ((List<Double>)io.github.wycst.wast.json.JSON.parse("[" + s + "]")).get(0);
>         System.out.println(d1); // 输出: 9.491136496029548E-309
>         double d2 = Double.parseDouble(s);
>         System.out.println(d2); // 输出: 9.49113649602955E-309
>         System.out.println(d1 == d2); // 输出: false
>     }
> ```
> 
> 另外, JSON.parse最好可以解析number,boolean字符串, 返回Number,Boolean类型.

bug已修复 ，Number,Boolean后续会考虑添加。

**Comment by dwing4g** [comment]
> bug已修复 ，Number,Boolean后续会考虑添加。

我刚试了一下, 那个数是正常了, 但发现还有很多浮点值出现了误差, 而且出现概率更大了.
我给你提供一个比较全面的浮点数测试:
```
    @SuppressWarnings("unchecked")
    public static void main(String[] args) {
        Random r = new Random();
        for (int i = 0; i < 10000000; i++) {
            long v;
            do
                v = r.nextLong();
            while ((v & 0x7ff0000000000000L) == 0x7ff0000000000000L); // 排除Infinity,NaN
            double d = Double.longBitsToDouble(v);
            double d1 = ((List<? extends Number>)io.github.wycst.wast.json.JSON.parse("[" + d + "]")).get(0).doubleValue();
            if (d != d1)
                throw new AssertionError("testRandomWastParser[" + i + "]: " + d + " != " + d1);
        }
        System.out.println("testRandomWastParser OK!");
    }
```

**Comment by wycst** [comment]
> > bug已修复 ，Number,Boolean后续会考虑添加。
> 
> 我刚试了一下, 那个数是正常了, 但发现还有很多浮点值出现了误差, 而且出现概率更大了. 我给你提供一个比较全面的浮点数测试:
> 
> ```
>     @SuppressWarnings("unchecked")
>     public static void main(String[] args) {
>         Random r = new Random();
>         for (int i = 0; i < 10000000; i++) {
>             long v;
>             do
>                 v = r.nextLong();
>             while ((v & 0x7ff0000000000000L) == 0x7ff0000000000000L); // 排除Infinity,NaN
>             double d = Double.longBitsToDouble(v);
>             double d1 = ((List<? extends Number>)io.github.wycst.wast.json.JSON.parse("[" + d + "]")).get(0).doubleValue();
>             if (d != d1)
>                 throw new AssertionError("testRandomWastParser[" + i + "]: " + d + " != " + d1);
>         }
>         System.out.println("testRandomWastParser OK!");
>     }
> ```

好的3q

**Comment by wycst** [comment]
> > bug已修复 ，Number,Boolean后续会考虑添加。
> 
> 我刚试了一下, 那个数是正常了, 但发现还有很多浮点值出现了误差, 而且出现概率更大了. 我给你提供一个比较全面的浮点数测试:
> 
> ```
>     @SuppressWarnings("unchecked")
>     public static void main(String[] args) {
>         Random r = new Random();
>         for (int i = 0; i < 10000000; i++) {
>             long v;
>             do
>                 v = r.nextLong();
>             while ((v & 0x7ff0000000000000L) == 0x7ff0000000000000L); // 排除Infinity,NaN
>             double d = Double.longBitsToDouble(v);
>             double d1 = ((List<? extends Number>)io.github.wycst.wast.json.JSON.parse("[" + d + "]")).get(0).doubleValue();
>             if (d != d1)
>                 throw new AssertionError("testRandomWastParser[" + i + "]: " + d + " != " + d1);
>         }
>         System.out.println("testRandomWastParser OK!");
>     }
> ```

这次应该没问题了，版本会尽快发。

**Comment by wycst** [comment]
> 解析少部分浮点数字符串有精度问题, 跟JDK自带的解析不一致:
> 
> ```
>     public static void main(String[] args) {
>         double d = 9.49113649602955E-309;
>         String s = Double.toString(d);
>         System.out.println(s); // 输出: 9.49113649602955E-309
>         double d1 = ((List<Double>)io.github.wycst.wast.json.JSON.parse("[" + s + "]")).get(0);
>         System.out.println(d1); // 输出: 9.491136496029548E-309
>         double d2 = Double.parseDouble(s);
>         System.out.println(d2); // 输出: 9.49113649602955E-309
>         System.out.println(d1 == d2); // 输出: false
>     }
> ```
> 
> 另外, JSON.parse最好可以解析number,boolean字符串, 返回Number,Boolean类型.

v0.0.20版本更新了,解析number和boolean类型可以使用JSON.parseAs或者JSON.parseNumberAs代码如下
```
        double d = 9.49113649602955E-309;
        String s = Double.toString(d);

        {
            double d2 = JSON.parseAs(s);
            System.out.println(d2 == d);
            boolean flag1 = JSON.parseAs("true");
            System.out.println(flag1 == true);
            boolean flag2 = JSON.parseAs("false");
            System.out.println(flag2 == false);
            System.out.println(JSON.parseAs("null") == null);
        }
```

**Comment by dwing4g** [comment]
> v0.0.20版本更新了,解析number和boolean类型可以使用JSON.parseAs或者JSON.parseNumberAs代码如下

试过没问题了, JSON.parse也可以解析number和boolean了.
